const root=document.querySelector('#architectureExplorer');
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colours={renderer:'#70a9ef',main:'#e17d5b',injected:'#b991f1',external:'#52bd88'};
async function init(){
 const response=await fetch('./data/forge-architecture.json');
 if(!response.ok)throw new Error('Architecture data unavailable');
 const data=await response.json(),nodes=new Map(data.nodes.map(n=>[n.id,n]));
 root.innerHTML=`<div class="map-intro"><p>${escape(data.meta.description)}</p><span>${data.nodes.length} components · ${data.edges.length} connections · ${data.flows.length} traced workflows · source snapshot ${escape(data.meta.generated)}</span></div><div class="map-controls"><label>Trace a workflow<select id="mapFlow"><option value="all">All components</option>${data.flows.map(f=>`<option value="${escape(f.id)}">${escape(f.label)}</option>`).join('')}</select></label><label>Map scale<input id="mapScale" type="range" min="45" max="100" value="65"></label><a href="./data/forge-architecture.json" download>Download reference JSON</a></div><div class="map-legend">${data.contexts.map(c=>`<span style="--context:${colours[c.id]}">${escape(c.label)}</span>`).join('')}</div><div class="map-canvas"><svg id="systemMap" viewBox="0 0 2020 1410" role="img" aria-label="Forge component map"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#aaa"/></marker></defs>${data.groups.map(g=>`<g class="map-group"><rect x="${g.x}" y="${g.y}" width="${g.w}" height="${g.h}" rx="12"/><text x="${g.x+12}" y="${g.y+24}">${escape(g.label)}</text></g>`).join('')}${data.edges.map(e=>{const a=nodes.get(e.from),b=nodes.get(e.to);if(!a||!b)return '';const forward=b.x>=a.x;const ax=forward?a.x+a.w:a.x,bx=forward?b.x:b.x+b.w,ay=a.y+a.h/2,by=b.y+b.h/2;const bend=Math.max(45,Math.abs(bx-ax)*.45);return `<path class="map-edge" data-edge="${escape(e.id)}" d="M${ax} ${ay} C${ax+(forward?bend:-bend)} ${ay},${bx-(forward?bend:-bend)} ${by},${bx} ${by}" marker-end="url(#arrow)"><title>${escape(e.label)}${e.note?' — '+escape(e.note):''}</title></path>`}).join('')}${data.nodes.map(n=>`<g class="map-node" data-node="${escape(n.id)}" tabindex="0" role="button" aria-label="${escape(n.label)}"><rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="8" style="stroke:${colours[n.context]||'#aaa'}"/><text x="${n.x+10}" y="${n.y+25}">${escape(n.label.length>25?n.label.slice(0,24)+'…':n.label)}</text><text class="map-node-kind" x="${n.x+10}" y="${n.y+47}">${escape(n.kind)} · ${escape(n.context)}</text><title>${escape(n.summary)}</title></g>`).join('')}</svg></div><div class="map-detail-grid"><article id="mapTrace"></article><aside id="mapComponent"></aside></div><details class="map-invariants"><summary>Implementation invariants and known constraints</summary><ul>${data.meta.invariants.map(x=>`<li>${escape(x)}</li>`).join('')}</ul></details>`;
 const svg=root.querySelector('#systemMap'),trace=root.querySelector('#mapTrace'),component=root.querySelector('#mapComponent');
 function showNode(id){const n=nodes.get(id);if(!n)return;component.innerHTML=`<p class="overline">COMPONENT · ${escape(n.context)}</p><h3>${escape(n.label)}</h3><p>${escape(n.summary)}</p><div class="map-tags">${(n.tech||[]).map(t=>`<span>${escape(t)}</span>`).join('')}</div><small>Source reference: ${escape(n.file)}${n.line?':'+n.line:''}</small>`;root.querySelectorAll('.map-node').forEach(el=>el.classList.toggle('chosen',el.dataset.node===id));}
 function selectFlow(id){const flow=data.flows.find(f=>f.id===id),active=new Set(flow?.steps.map(s=>s.node)||[]),edges=new Set(flow?.steps.map(s=>s.edge).filter(Boolean)||[]);data.edges.filter(e=>edges.has(e.id)).forEach(e=>{active.add(e.from);active.add(e.to)});root.querySelectorAll('.map-node').forEach(el=>el.classList.toggle('dimmed',!!flow&&!active.has(el.dataset.node)));root.querySelectorAll('.map-edge').forEach(el=>{el.classList.toggle('dimmed',!!flow&&!edges.has(el.dataset.edge));el.classList.toggle('traced',edges.has(el.dataset.edge))});trace.innerHTML=flow?`<p class="overline">WORKFLOW · ${escape(flow.entry)}</p><h3>${escape(flow.label)}</h3><p>${escape(flow.summary)}</p><ol class="map-steps">${flow.steps.map(s=>`<li><button data-step-node="${escape(s.node)}">${escape(s.label)}${s.guard?' <span>GUARD</span>':''}</button>${s.detail?`<p>${escape(s.detail)}</p>`:''}<small>${escape(s.file)}${s.line?':'+s.line:''}</small></li>`).join('')}</ol><h4>Failure modes</h4>${flow.failureModes.map(f=>`<details class="map-failure"><summary>${escape(f.symptom)}</summary><p><strong>Cause:</strong> ${escape(f.cause)}</p><p><strong>Check:</strong> ${escape(f.check)}</p><small>${escape(f.where)}</small></details>`).join('')}`:`<h3>Explore the implementation</h3><p>Select one of the 11 workflows to highlight its components and connections, then inspect its steps and failure modes. Click any component for its role and source reference.</p><p>The reference describes Forge's desktop implementation. The executable portfolio demo uses its own synthetic records and simulated adapters.</p>`;trace.querySelectorAll('[data-step-node]').forEach(button=>button.onclick=()=>showNode(button.dataset.stepNode));if(flow)showNode(flow.steps[0].node);}
 root.querySelectorAll('.map-node').forEach(el=>{el.onclick=()=>showNode(el.dataset.node);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showNode(el.dataset.node)}}});
 root.querySelector('#mapFlow').onchange=e=>selectFlow(e.target.value);
 const scale=root.querySelector('#mapScale');function resize(){svg.style.width=`${2020*Number(scale.value)/100}px`;svg.style.height=`${1410*Number(scale.value)/100}px`;}scale.oninput=resize;resize();selectFlow('all');
}
init().catch(error=>{root.textContent=error.message;});
